### ISSUE TITLE
Change contributing file name to CONTRIBUTING.md 

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-doc#111]
Change from qutip_dev_contrib.md to CONTRIBUTING.md to appear in the GH [community profile](https://github.com/qutip/qutip/community), as apparently standard.  Would need to change the file name and instances where it occurs (search for `qutip_dev_contrib` in Github).

**Comment by Alexios-xi** [comment]
@nathanshammah  I have opened this [PR](https://github.com/qutip/qutip/pull/1270) which will fix all the occurances of qutip_dev_contrib to CONTRIBUTING.md in the main branch of qutip.

**Comment by nathanshammah** [comment]
Closed by #112.
