### ISSUE TITLE
Add sphinx-doctest 

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-doc#115]
Using `sphinx-doctest` allows to test the examples in rst. The `doctest` directive for interactive code blocks allows to test examples. For static blocks this can be done with `testcode` (matched by `testoutput` and eventually with the ghost block `testsetup`).

**Comment by sarsid** [comment]
@nathanshammah, I am working on this now, will add a pr soon.

**Comment by jakelishman** [comment]
Done in #120
