### ISSUE TITLE
Add a list of libraries using qutip and qutip plugins

### ISSUE THREAD

**Issue by nathanshammah** [qutip/qutip-doc#122]
There are several libraries that rely on QuTiP for quantum physics or quantum information processing. Examples include [Krotov](https://github.com/qucontrol/krotov), [Matsubara](https://github.com/pyquantum/matsubara/tree/v0.1.4) and [PyEPR](https://github.com/zlatko-minev/pyEPR/tree/master/pyEPR). It would be nice to have a place in the documentation (and on the qutip website, possibly even beyond the documentation) where these are listed, with links taking to them and a short, one line description. 

A difference could be made in cathegorizing them between "libraries using QuTiP" and "QuTiP plugins" (they heavily rely on QuTiP for basic functionalities). 

The Github tool ["Used by"](https://github.com/qutip/qutip/network/dependents?package_id=UGFja2FnZS01MjUzMDIyMw%3D%3D) could be used for to find all of the former that are just not forks.

**Comment by tgag17** [comment]
Hey! I am new to QuTiP and would like to contribute to this enhancement.

**Comment by nathanshammah** [comment]
thanks a lot. please feel free to open a pull request. we'd need to edit one of the .rst files. as mentioned in the issue, some libraries could be picked up from the github 'Used by' tool. Others include:
- scqubits
- matsubara
-pyepr
- krotov
- https://github.com/Tomographer/tomographer/

**Comment by tgag17** [comment]
I think the libraries should be added after the About QuTiP subsection under the Frontmatter section. Any suggestions?

**Comment by nathanshammah** [comment]
Good idea. After "About QuTiP".
