### ISSUE TITLE
Building docs locally ?

### ISSUE THREAD

**Issue by purva-thakre** [qutip/qutip-doc#138]
How should I build docs locally ? 

I am making changes to docstrongs in `qutip/qutip` and I want to test the build. For this, I have a clone of `qutip/qutip` folder but the `makefile` is in `qutip-doc`. Should I clone `qutip-doc` in the local folder of `qutip/qutip` ?

**Comment by purva-thakre** [comment]
Closing this issue because I did not look in the right directory. Found the needed information [here](https://github.com/qutip/qutip-doc/blob/master/CONTRIBUTING.md#forking-and-cloning-repositories).

**Comment by purva-thakre** [comment]
Reopening because I did not figure this out as I initially thought. 

I want to run `make html` from `qutip/qutip-doc` in order to verify changes in API Doc when I make edits in `qutip/qutip`. Locally, I have a branch created from `qutip/qutip`. I cannot run `make html` from this branch because `make` instructions are in another repo but in the same directory.  

I found one method to go about this but I am not experienced enough to understand if this is a good method.  [This link](https://stackoverflow.com/a/16493707/10241324) discusses changes to the working directory and checking out a branch from the other repo.

**Comment by BoxiLi** [comment]
Currently, you should install qutip using development mode `python setup.py develop` (http://qutip.org/docs/latest/installation.html#direct-setuptools-source-builds). Then go to the qutip-doc repo and use `make html` under the doc repo. It will build the docs using the qutip installed, including your change.

In the future, we plan to move docs to the main qutip repo, which will allow CI tests for docs.

**Comment by purva-thakre** [comment]
Yes, I do have the development mode installed. I had issues using `make html` because it kept on using `master` from `qutip/qutip` instead of `qutip/some_branch` for the build. This made me think that I should checkout `qutip/some_branch` in docs repo and then run make commands which led me to above links. 

Guess I'll try `[make clean html](https://www.sphinx-doc.org/en/master/internals/contributing.html#debugging-tips)`. 

Another possible issue could be [my code editor.](https://atom.io/) I can preview `html` in this after a successful build and maybe the `_build` folder was not updated when I previewed it.

**Comment by BoxiLi** [comment]
> it kept on using master from qutip/qutip instead of qutip/some_branch for the build.

That's strange, if you checked out `qutip/some_branch` in the qutip repo, then `make html` should use that branch. I don't use Atom myself so I'm not sure about cache. I view the `html` files on Chrome and the only thing I need to do is refresh the page. Indeed try `make clean` first.

**Comment by purva-thakre** [comment]
Closing because the issue was related to Atom editor.
