### ISSUE TITLE
Outdated documentation on "Visualization of quantum states"

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip-doc#25]
[This page](http://qutip.org/docs/3.1.0/guide/guide-visualization.html) refers to `qutip.visualization.wigner_cmap` which does not seem to be available (see https://github.com/qutip/qutip/blob/master/qutip/visualization.py).

I guess it should use the `plot_wigner` function instead?

**Comment by nathanshammah** [comment]
Thank you. It seems that `wigner_cmap` has been moved from `visualization` to `matplotlib_utilities`. We could fix the way this is called in the User Guide and see how to include this in the API.
