### ISSUE TITLE
Document Non-Markovian Module

### ISSUE THREAD

**Issue by nonhermitian** [qutip/qutip-doc#29]

**Comment by nathanshammah** [comment]
In API doc, the `nonmarkov` classes and functions are present. 
API doc > Functions:
- ttmsolve

API doc > Classes:
- HEOMSolver
- HSolverDL
- MemoryCascade
- TTMSolverOptions
Will ask Neill and @quantshah if they have some tutorials and can add some information on the User Guide in the future as they might be working on this and an extension.
