### ISSUE TITLE
Extraneous backslashes in latexpdf ipython output

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip-doc#44]
There are a lot of backslashes in the place of where `[OUT]` would expected to be seen in the ipython generated latex. 
For example:
```
\PYG{g+go}{\PYGZbs{}\PYGZbs{}\PYGZbs{}\PYGZbs{}\PYGZbs{}\PYGZbs{}\PYGZbs{}\PYGZbs{}\PYGZbs{}\PYGZbs{}
```
(this actually goes on much longer, I just copied a fraction of it)

Does not appear in the HTML output

**Comment by jakelishman** [comment]
Fixed by #120
