### ISSUE TITLE
Instructions for installing on Windows with Python 2.7 / 3.4 

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip-doc#49]
@nonhermitian I am very happy with the idea that we state clearly that we will only offer support for qutip on Windows using Python 3.5+ and Visual Studio as the compiler. However, there are some users who don't have the ~10GB free needed for Visual Studio 2015. I have just been helping such a student here.

I see in the latest version of the installation docs we no longer give any information on installing qutip on Windows with Python 2.7 / 3.4. Can I add something on distutils.cfg and mingwpy? This seems to work ok with the new c++ extensions.

**Comment by nonhermitian** [comment]
I have no problem with that. However, we should keep the number of
combinations to a minimum.  Py34 is no longer even supported as a conda
branch, so at least that should be dropped.

-P

**Comment by ajgpitch** [comment]
Ok. Yes, I see now that conda-forge is not creating any py34 packages. Thanks for spotting that.
I will update the instructions then to describe how to install for py27

**Comment by ajgpitch** [comment]
Done
