### ISSUE TITLE
Undocumented Floquet functions

### ISSUE THREAD

**Issue by Phyks** [qutip/qutip-doc#54]
Hi,

It seems some of the functions in the `qutip.floquet` module are not documented in the doc. For instance, for `qutip.floquet.floquet_master_equation_rates`, [there is no found documentation](http://qutip.org/docs/4.1/search.html?q=floquet_master_equation_rates&check_keywords=yes&area=default).

Not sure if this is on purpose or not, especially since [these functions should have a valid docstring](https://github.com/qutip/qutip/blob/master/qutip/floquet.py#L540-L590).

EDIT: This is also the case for many other functions in `qutip.floquet` module, such as `qutip.floquet.steadystate` which seems to be really useful.

**Comment by nathanshammah** [comment]
Thank you. Investigating.

**Comment by nathanshammah** [comment]
PR #68 addresses this. Should be reflected from QuTiP 4.4.

**Comment by ajgpitch** [comment]
Resolved by #68
