### ISSUE TITLE
Quantum optimal control section missing references

### ISSUE THREAD

**Issue by webstersc** [qutip/qutip-doc#56]
The documentation for quantum optimal control has numerous numbered references within the text, however there is no bibliography detailing what papers are being referenced.

**Comment by ajgpitch** [comment]
I see the bibliography just fine in
http://nbviewer.jupyter.org/github/qutip/qutip-notebooks/blob/master/examples/optimal-control-overview.ipynb
. @webstersc do you want to send me the link you are referring to?

**Comment by webstersc** [comment]
I'm looking in the documentation on the qutip site: [http://qutip.org/docs/latest/guide/guide-control.html](http://qutip.org/docs/latest/guide/guide-control.html)

It looks like the html documentation is based on an earlier version of the notebook you posted a link to.

**Comment by ajgpitch** [comment]
Yes, I see what you mean. Looks like I need to add the control refs to the main bibliography and link.
There are a few other little issues too (missing images etc)
I'll tidy it up.
Thanks for pointing this out

**Comment by ajgpitch** [comment]
I have now fixed the citation links, and added the image links.
@webstersc  Thanks again for notifying us about this
