### ISSUE TITLE
Document Models - PIQS

### ISSUE THREAD

**Issue by ajgpitch** [qutip/qutip-doc#58]
@nathanshammah @sahmed95
Documentation is required for Models and specifically PIQS

Does not need a lot. Can just copy some stuff from the intro notebook
Also the module needs linking for the API docs

**Comment by nathanshammah** [comment]
We can also integrate the information of the introductory notebook by
including info found in the readme of https://github.com/nathanshammah/piqs
@sahmed95 can you take care of this and of the linking for the API docs
(when you get the opportunity)?

2018-03-20 1:48 GMT+09:00 Alexander Pitchford <notifications@github.com>:

**Comment by ajgpitch** [comment]
@nathanshammah @quantshah We did have documentation from Ben for the scattering, so we really should have made a new build and published. Are you able to do a little something for piqs?

**Comment by nathanshammah** [comment]
#65
