### ISSUE TITLE
Update the API visualisation tree 

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip-doc#63]
The beautiful tree-diagram of the user accessible functions and classes have not been updated for a long time. I am trying to understand how it is visualized using D3.js and possibly writing an automated script to update it with new documentation. For now, I would suggestion removing it from the documentation and it is outdated.

http://qutip.org/docs/latest/guide/guide-overview.html#figure-qutip-org

**Comment by ajgpitch** [comment]
Seems like a good suggestion. @nathanshammah and I are trying to get a v4.3 of docs out, so we will remove it from that. Hopefully we can get it back in by v4.4

**Comment by nathanshammah** [comment]
#65
