### ISSUE TITLE
Duplicate entry for 'Monte Carlo Solver' in html doc sidebar

### ISSUE THREAD

**Issue by SamWolski** [qutip/qutip-doc#86]
![Screen Shot 2019-09-04 at 10 00 43](https://user-images.githubusercontent.com/22050575/64218017-de67c800-cefa-11e9-86ca-3ee5b76af71c.png)

As can be seen in the image, there is a duplicate entry for 'Monte Carlo Solver' in the sidebar of the html documentation. It appears on different browsers and operating systems, so I believe it to be a misconfiguration in the docs themselves.

I'm happy to work on this, although I don't have much experience with sphinx.

**Comment by nathanshammah** [comment]
Dear @SamWolski, thank you for spotting this; catching up with this only now. It is very simple: could you remove the repeated line in [`guide-dynamics.rst`](https://github.com/qutip/qutip-doc/blob/master/guide/guide-dynamics.rst)?

**Comment by SamWolski** [comment]
No worries, I'm on it. Expect a PR soon.
