### ISSUE TITLE
Update qutip

### ISSUE THREAD

**Issue by Hosseinyeganeh** [qutip/qutip-doc#93]
Hi 
I can't update qutip to last version 
What I do?

**Comment by nathanshammah** [comment]
We need more information on your machine, sotware details, in order to help out. You can join the forum [here](https://groups.google.com/forum/#!forum/qutip) for troubleshooting.

**Comment by Hosseinyeganeh** [comment]
you can say about command that used for updated?

**Comment by nathanshammah** [comment]
yes (conda install qutip, or pip install qutip, etc..), and what machine you have (Linux, Mac, Windows), what qutip version, and what error message. Also, more details on the other software versions on your machine.

**Comment by Hosseinyeganeh** [comment]
Thanks  I fixed
